version: '2'
services:
    zoo1:
        container_name: zoo1
        image: zookeeper:3.4.10
        restart: always
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo2:
        container_name: zoo2
        image: zookeeper:3.4.10
        restart: always
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    zoo3:
        container_name: zoo3
        image: zookeeper:3.4.10
        restart: always
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

    # kfka:
    #     container_name: kfka
    #     image:  kafkeeper
    #     restart: always
    #     links:
    #       - zoo1
    #       - zoo2
    #       - zoo3
